blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/Ali-Meh619/System_Design_ML_Principles/discussions
    about: Use discussions for open-ended design debates.
